# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
        ('bucket_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlistitem',
            name='votes',
            field=models.ManyToManyField(to='vote.Vote'),
        ),
    ]
