# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
        ('bucket_list', '0003_auto_20161121_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket_list',
            name='trip',
        ),
        migrations.AddField(
            model_name='bucket_list',
            name='trip_location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='trip.TripLocation'),
            preserve_default=False,
        ),
    ]
