"""
Django settings for tripplanner project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from _settings.common import *


try:
    from _settings.local import *
except ImportError:
    from _settings.production import *
