# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
