# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='emoji',
            field=models.CharField(choices=[('U+1F600', 'Smile'), ('U+1F60D', 'Heart Face'), ('U+1F608', 'Evil Face'), ('U+1F44D', 'Thumbs Up'), ('U+1F44E', 'Thumbs Down'), ('U+2764', 'Heart'), ('U+1F389', 'Party')], max_length=7),
        ),
    ]
