# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlistitem',
            old_name='completed',
            new_name='is_complete',
        ),
    ]
