# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlist', '0002_auto_20161120_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
