# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_triplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplocation',
            name='arrive',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triplocation',
            name='depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
