# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20161019_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
