# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20161019_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
