# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_jwt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userjwt',
            old_name='jwt_sub',
            new_name='sub',
        ),
    ]
